name: Trigger auto deployment for hero5000meledak

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hero5000meledak-AutoDeployTrigger-517d85a5-88a5-4009-b540-d1cdd07306e4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.HERO5000MELEDAK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HERO5000MELEDAK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HERO5000MELEDAK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.HERO5000MELEDAK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HERO5000MELEDAK_REGISTRY_PASSWORD }}
          containerAppName: hero5000meledak
          resourceGroup: hero5000meledak
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


